# Generated by Django 4.2.1 on 2023-05-15 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageMessage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('message', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'message_message',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
