# Generated by Django 4.2.1 on 2023-05-15 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0003_message_delete_messagemessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'managed': False},
        ),
    ]
